spring.application.name=investment-platform

spring.datasource.url=jdbc:mysql://localhost:3306/investment_db
spring.datasource.username=root
spring.datasource.password=Rishu@mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

nav.provider.base-url=https://api.mfapi.in
nav.provider.timeout=5000